from __future__ import annotations

from embodied_stack.shared.models import CompanionBehaviorCategory

from .types import SkillSpec


COMMUNITY_CONCIERGE: tuple[SkillSpec, ...] = (
    SkillSpec(
        name="welcome_guest",
        playbook_name="community_concierge",
        route_variant="welcome_guest",
        behavior_category=CompanionBehaviorCategory.VENUE_CONCIERGE,
        description="Warm, grounded first-contact responses for a new arrival.",
        purpose="Greet briefly and establish the robot's help scope without repeating itself.",
        required_tools=("system_health", "search_memory", "world_model_runtime", "body_preview"),
        allowed_tools=("system_health", "search_memory", "memory_status", "world_model_runtime", "body_preview"),
        forbidden_claims=("I can walk you there",),
        success_criteria=("greet briefly", "state help scope", "avoid repeated auto-greeting"),
        entry_conditions=("The conversation is new or clearly greeting-oriented.",),
        exit_conditions=("The greeting establishes scope and next-step help.",),
        body_style_hints=("friendly", "look_at_user"),
        memory_rules=("Use remembered name only if already stored.",),
        evaluation_rubric=("Warmth", "Scope honesty", "No repetitive greeting"),
        aliases=("community_concierge",),
    ),
    SkillSpec(
        name="wayfinding",
        playbook_name="community_concierge",
        route_variant="wayfinding",
        behavior_category=CompanionBehaviorCategory.VENUE_CONCIERGE,
        description="Grounded room and landmark guidance.",
        purpose="Give concrete directions using venue knowledge and visible anchors.",
        required_tools=("search_venue_knowledge", "world_model_runtime", "device_health_snapshot", "system_health", "body_preview"),
        allowed_tools=("search_venue_knowledge", "query_calendar", "world_model_runtime", "device_health_snapshot", "system_health", "body_preview"),
        forbidden_claims=("I can physically lead you there",),
        success_criteria=("use confirmed venue facts", "stay directionally concrete"),
        entry_conditions=("The visitor asks where something is.",),
        exit_conditions=("Directions cite known landmarks or clearly state missing information.",),
        body_style_hints=("listen_attentively", "look_forward"),
        memory_rules=("Remember route preferences if the user states them.",),
        evaluation_rubric=("Directional clarity", "Grounding", "Capability honesty"),
    ),
    SkillSpec(
        name="schedule_help",
        playbook_name="community_concierge",
        route_variant="schedule_help",
        behavior_category=CompanionBehaviorCategory.VENUE_CONCIERGE,
        description="Grounded event and schedule help.",
        purpose="Answer schedule and event timing questions from imported site data.",
        required_tools=("query_calendar", "system_health"),
        allowed_tools=("query_calendar", "search_venue_knowledge", "system_health", "body_preview"),
        forbidden_claims=("I can book that for you",),
        success_criteria=("cite imported schedule facts", "be honest when schedule is missing"),
        entry_conditions=("The visitor asks about events or timing.",),
        exit_conditions=("The answer cites schedule facts or reports absence clearly.",),
        body_style_hints=("listen_attentively", "brief"),
        memory_rules=("Do not fabricate commitments or reservations.",),
        evaluation_rubric=("Schedule grounding", "Clarity", "No invented bookings"),
        aliases=("calendar_lookup",),
    ),
    SkillSpec(
        name="workspace_context_help",
        playbook_name="community_concierge",
        route_variant="workspace_context_help",
        behavior_category=CompanionBehaviorCategory.GENERAL_CONVERSATION,
        description="Use recent notes and digests to help with current local workspace context.",
        purpose="Ground coding or work recap to saved notes and recent session digests.",
        required_tools=("query_local_files", "recent_session_digest", "search_memory", "memory_status"),
        allowed_tools=("query_local_files", "recent_session_digest", "search_memory", "memory_status"),
        forbidden_claims=("I searched external systems I did not access",),
        success_criteria=("prefer recent notes", "stay grounded to saved local context"),
        entry_conditions=("The user asks about local workspace context or recent work.",),
        exit_conditions=("The recap is grounded to saved local artifacts.",),
        body_style_hints=("technical", "brief"),
        memory_rules=("Prefer recent session digests over stale notes.",),
        evaluation_rubric=("Recency", "Grounding", "Scope honesty"),
    ),
)
